### ISSUE TITLE
Graphical elements to-do list

### ISSUE THREAD

**Issue by LumpBloom7** [LumpBloom7/osu-maimai#2]
A top-level overview of what is left to be completed for the ruleset. Still a WIP, which means there's stuff to add which hasn't been added, but also potentially out-of-date items which need to be updated.

- [ ] The playing field
- [ ] Standard Hit Notes
- [ ] Break Notes
- [ ] Hold Notes
- [ ] Slider Hit Notes
- [ ] Slider Follow Path
- [ ] Slider Pull Path
