### ISSUE TITLE
Audio elements to-do list

### ISSUE THREAD

**Issue by LumpBloom7** [LumpBloom7/osu-maimai#3]
A top-level overview of what is left to be sounded for the gameplay elements. Still a WIP, which means there's stuff to add which hasn't been added, but also potentially out-of-date items which need to be updated.

Some of these could definitely use the osu!standard hitsounds, the only thing we would need the sound is the elements that are unique to maimai.

- [ ] Standard Hit Notes
- [ ] Break Notes
- [ ] Hold Notes
- [ ] Slider Hit Notes
- [ ] Slider Follow Path
- [ ] Slider Pull Path
